openapi: 3.0.3

info:
  title: Subscription API
  version: 1.0.0

components:
  schemas:
    User:
      type: object
      required:
        - user_id
        - pseudo
      properties:
        user_id:
          type: string
        pseudo:
          type: string