openapi: 3.0.3

info:
  title: Subscription API
  version: 1.0.0

components:
  schemas:
    User:
      type: object
      required:
        - user_id
        - pseudo
      properties:
        user_id:
          type: string
        pseudo:
          type: string
    LNChallenge:
      type: object
      required:
        - lnurl
        - k1
      properties:
        lnurl:
          type: string
        k1:
          type: string
    LNCallbackSuccessPayload:
      type: object
      reaquired:
        - status
        - refresh_token
        - access_token
      properties:
        status:
          type: string
        refresh_token:
          type: string
        access_token:
          type: string